 skinparam class {
    BackgroundColor Azure
    ArrowColor SteelBlue
    BorderColor SteelBlue
}

skinparam Note{
    BackgroundColor Teal
    BorderColor Teal
    FontColor White
}

skinparam ArrowFontColor DarkGray
skinparam PackageBackgroundColor Gainsboro
